### ISSUE TITLE
Syncing Newly added columns

### ISSUE THREAD

**Issue by mitulmakadia** [tgropper/ElasticSearchSync#1]
We have a use case where 15 millions records are there in SQL Sever in a table and ES is already in sync. We just added a new field in table. Can this library smartly handle updates in ES ?

**Comment by tgropper** [comment]
Hi, I'm sorry but I'm not maintaining this project anymore. Feel free of making any change you want and create a PR!

Despite that, I looked at the code and it seems that if you use the [PageSize config](https://github.com/tgropper/ElasticSearchSync/blob/master/ElasticSearchSync/SyncConfiguration.cs#L46) the sync process executes the SqlCommand N times until it reaches the end, but calculating it in each run. So I guess it should read new rows, unless they are added after the last SqlCommand started its execution.

Hope this helps you!

**Comment by tgropper** [comment]
Sorry I've just read again the issue title and you are trying to add new columns while running, not rows.
The SqlCommand is static since it is [configured](https://github.com/tgropper/ElasticSearchSync/blob/master/ElasticSearchSync/SyncConfiguration.cs#L17) before the process starts, so I guess it is not possible to handle this new columns.
The only workaround I can think of is using `SELECT *`+`PageSize`, but I'm not sure if this will break something else.

Another less happy workaround is to re-index everything, deleting the log documents from elastic to start all over again.

**Comment by mitulmakadia** [comment]
Thanks Tomás!
